version: "3.8"

services:
  discord-bot:
    image: ghcr.io/yourusername/halaproject-discordbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: halaproject-discordbot
    restart: unless-stopped
