version: "3.8"

services:
  discord-bot:
    image: ghcr.io/halaproject/discordbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: discordbot
    restart: unless-stopped
